services:
  nats:
    image: nats:2.10-alpine
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    command: [
        '--js', # Enable JetStream
        '--sd',
        '/data', # Store directory
        '--http_port',
        '8222', # Monitoring port
      ]
    volumes:
      - nats_data:/data
    networks:
      - microservices

volumes:
  nats_data:

networks:
  microservices:
    driver: bridge
